[package]
name = "max-media"
version.workspace = true
edition.workspace = true

[dependencies]
max-api.workspace = true
image.workspace = true
thiserror.workspace = true

[target.'cfg(target_os = "macos")'.dependencies]
block2.workspace = true
dispatch2.workspace = true
objc2.workspace = true
objc2-quartz-core.workspace = true
objc2-core-graphics.workspace = true
objc2-foundation.workspace = true
objc2-av-foundation.workspace = true
objc2-core-video.workspace = true
objc2-core-media.workspace = true

[lints]
workspace = true
